[package]
name = "font_metrics"
version = "0.1.0"
authors = ["Jack Willis <jack@attac.us>"]

[dependencies]
clap = "2.31"
lopdf = "0.15"
num-rational = "0.1"
pdf-extract = "0.4"
rusttype = "0.6"

[dev-dependencies]
just = "0.3"

[lib]
name = "font_metrics"
path = "src/lib.rs"

[[bin]]
name = "xheight"
path = "bin/xheight.rs"

[[bin]]
name = "cpp"
path = "bin/cpp.rs"